### ISSUE TITLE
[Bug] Color returns to black if the cursor drags out of the window

### ISSUE THREAD

**Issue by nahuelwexd** [lainsce/colorway#3]
Video attached

Version: 1.0.2

https://user-images.githubusercontent.com/18204745/139284536-432437b5-9048-4e11-915f-0387bf29ca44.mp4

**Comment by dusansimic** [comment]
@lainsce 

> to avoid an out of bounds bug

Instead of returning to `#000000` it might be better to save the last picked location. Since the color code is changed as the cursor is dragged across the picker, it might be good that if the cursor is released out of bounds, the last picked color is actually used, not `#000000`. That's at least how [gcolor3](https://gitlab.gnome.org/World/gcolor3) and most other color pickers ([random web based color picker](https://htmlcolorcodes.com/color-picker/)) behave. To be completely honest, I think that's what issue author expected and so did I.

**Comment by lainsce** [comment]
I see, now it became more clear what was asked. :P

I'll see what I can do.
